### ISSUE TITLE
Idea: Option to use geometry of overlapping shapes to make closed polygons on overlapped shapes

### ISSUE THREAD

**Issue by jayde-d** [LoicGoulefert/occult#24]
It may be useful for people using commands like `fill` from [here](https://github.com/abey79/vpype-explorations) (which may become a feature in vpype depending on whenever that happens) or `efill` from [the embroidery plugin](https://github.com/EmbroidePy/vpype-embroidery), to be able to make overlapping shapes be cropped properly, but have the resulting design use closed polygon loops, which these functions need to define their bounds. Not a massive necessity and i've not poked about your source code to see how feasible this would be, but I think it could be a great addition to this plugin. Threw a rough vis image together to show what this may look like. (please ignore that i was too lazy to reauthor the svg to make it have a filled shape, so the filled lines is just copy paste job :') )
![idea_pic](https://user-images.githubusercontent.com/30290302/206233264-b1c11ab4-bd7e-4eaf-a0d7-d28fa3e12a4f.png)

**Comment by LoicGoulefert** [comment]
Hi @jayde-d ! I'm not sure this would be a good feature to have in occult. This plugin main goal is to remove geometries, not add them. Then again I'm not sure I fully understood your idea !

**Comment by JulienPlume** [comment]
Hello everyone, 
I'm struggling to create 2 distinct shapes from 2 overlapping shapes. 
I use Occult with great pleasure (thank you very much) to plot my work from p5.js ([with the SVG mode](https://github.com/zenozeng/p5.js-svg)). 
Occult works perfectly well for outlines. 
Now I want to add background color - hatch fill plugin on inkscape) but I need a solution for finished shapes so that the colors don't overlap.

It's easy to do that on Inkscape for 2 shapes, but I have several hundred per file.

Have fun !
